### ISSUE TITLE
得到的数据怎么显示在html的img里呢？

### ISSUE THREAD

**Issue by buzai** [zengming00/node-gd-bmp#2]
按照你的demo，把最后的数据给前端，前端把数据给img的src，不显示图片啊

**Comment by zengming00** [comment]
你有没有设置content-type?
```js
res.set('Content-Type', 'image/bmp');
res.send(img.getFileData());
```

**Comment by buzai** [comment]
@zengming00   我是直接返回的数据 res.json( { img : img.getFileData() } )

**Comment by zengming00** [comment]
这样用的话，你需要转成data url才可以
```js
res.json({
    img: 'data:image/bmp;base64,' + img.getFileData().toString('base64')
})
```

**Comment by buzai** [comment]
sogou 谢谢了啊

**Comment by fritx** [comment]
Hey，打扰了，我给koa写了个基于这个的utils，感兴趣的可以用一下：
https://github.com/fritx/koa-captcha-2

**Comment by buzai** [comment]
@fritx 谢谢，正好换到ｋｏａ，话说大佬你是ｑｉｕｓｈｉｂａｉｋｅ的？

**Comment by fritx** [comment]
@buzai 哈哈，我以前在糗百实习，你呢？
