### ISSUE TITLE
更改背景顏色

### ISSUE THREAD

**Issue by LuHua10** [zengming00/node-gd-bmp#4]
樓主大大你好,想請問根據以下程式碼,所產生的背景

let img = new BMP24(100, 40);

要如何更改背景色呀？

看了源碼,發現看不太懂 orz

感謝回答

**Comment by zengming00** [comment]
用img.fillRect(x1, y1, x2, y2, rgb)方法填充整个图片

**Comment by LuHua10** [comment]
太感謝你了!!!

**Comment by THROFHR** [comment]
👌，谢谢
